### ISSUE TITLE
add subcharts as submodules

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda-chart#1]
subcharts are not included as submodules, and require manual effort to add

**Comment by volodymyrss** [comment]
I added two of the subcharts, as well as some comments.

**Comment by cavet** [comment]
Still not working for dispatcher, the commit number is unavailable:
% git clone --recurse-submodules https://github.com/cdcihub/oda-chart.git
Clonage dans 'oda-chart'...
...
Sous-module 'charts/dda-chart' (git@github.com:cdcihub/dda-chart.git) enregistré pour le chemin 'charts/dda-chart'
Sous-module 'charts/dispatcher-chart' (git@github.com:cdcihub/dispatcher-chart.git) enregistré pour le chemin 'charts/dispatcher-chart'
Clonage dans '/.../oda-chart/charts/dda-chart'...
Chemin de sous-module 'charts/dda-chart' : '583e7ef4f040abadb751b10757a333d31585c3d9' extrait
fatal: erreur distante : upload-pack: not our ref 76b03b90720ee99b611c85c8b3b85f53a7b52d56
Chemin de sous-module 'charts/dispatcher-chart' récupéré, mais il ne contenait pas 76b03b90720ee99b611c85c8b3b85f53a7b52d56. La récupération directe de ce commit a échoué.

**Comment by volodymyrss** [comment]
I pushed the lacking commits to github. Now the submodules links resolve, also seen in github interface.

**Comment by cavet** [comment]
you can close this issue
