### ISSUE TITLE
improve portability

### ISSUE THREAD

**Issue by cavet** [oda-hub/oda-chart#2]
lot of hard link in dda-chart and dispatcher chart, see values.yaml and deployment.yaml

**Comment by volodymyrss** [comment]
Yeah, I will make an option to move all to persistent volumes. 
There is a complexity that I can not use values from another values. As far as I know.

**Comment by volodymyrss** [comment]
by the way, in principle, one can skip the /ddcache directory entirely, since it is used in addition to minio datalake, which is a better  way do do this sharing.

**Comment by volodymyrss** [comment]
I should make some sort of effort to remove those things, since they are not necessary.
